### ISSUE TITLE
No requirements file

### ISSUE THREAD

**Issue by edmorley** [avih/talos_validator#1]
Hi!

I'm making a list of projects that use treeherder-client, to make it easier to track who to inform in case of proposed API changes/deprecation etc. I don't know whether this project is under active development or not, but since there is no requirements file, it's hard to know what version you are using. If this project is still active, creating a requirements file would let me file issues (or even open PRs) when we deprecate old versions of the client.

Many thanks :-)

**Comment by avih** [comment]
It doesn't use treeherder client. This project independently cross-validates the calculations which talos performs and perfherder displays - by parsing the log file which talos generates and applying the expected formulas independently.

However, for it to be reasonably useful, the web servers which host the talos logs need not block requests from external sites. They used to allow access from external sites but not anymore, so it's harder to use this tool effectively these days.

Solutions could include downloading the log file first, or hosting this project in a domain which the log web servers allow access from.

One such log example URL would be https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-inbound-macosx64/1452592555/mozilla-inbound_yosemite_r7_test-g2-bm106-tests1-macosx-build779.txt.gz and an example of the analysis which used to work but not anymore due to this blocked access is: https://rawgit.com/avih/talos_validator/master/parse-talos-log.html#log=https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-inbound-macosx64/1452592555/mozilla-inbound_yosemite_r7_test-g2-bm106-tests1-macosx-build779.txt.gz

This project might have become stale, but since it's not practical to use it externally anymore, it doesn't matter much.

**Comment by edmorley** [comment]
> It doesn't use treeherder client.

This script does:
https://github.com/avih/talos_validator/blob/5e8125be0cfe314f932aac2e4c174e8e750d2a63/test-client.py#L16

> This project might have become stale, but since it's not practical to use it externally anymore, it doesn't matter much.

Ok, sounds good to me :-)

**Comment by avih** [comment]
> This script does:
> https://github.com/avih/talos_validator/blob/5e8125be0cfe314f932aac2e4c174e8e750d2a63/test-client.py#L16

Indeed, and I added it to the repo as an example of using the client - it's not used, however, the project's only real work is parsing talos logs and validating them independently.
